export type IItem = {
  id?: number;
  name: string;
  supplier_id?: number | null;
  type_id?: number | null;
  category_id?: number | null;
  location_id?: number | null;
  description?: string | null;
  unit?: string;
  tag_ids: number[];
  image_urls: string[];
  stock_quantity?: number;
  min_stock: number;
  max_stock: number;
  expiry_date?: Date | null;
  cost_per_unit?: number;
  last_restocked: Date | null;
  shelf_life?: number | null;
  storage_conditions?: string | null;
  temperature_range?: string | null;
  humidity_range?: string | null;
  status: 'active' | 'inactive' | 'expired' | 'archived';
  batch_tracking_enabled: boolean;
  note?: string | null;
  created_at?: Date;
  updated_at?: Date;
};
