export type ISupplier = {
  id?: string;
  name: string;
  description?: string | null;
  contact_person?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  city?: string | null;
  country?: string | null;
  tax_id?: string | null;
  payment_terms?: string | null;
  credit_limit?: number | null;
  current_balance?: number | null;
  status?: 'active' | 'inactive' | 'blacklisted';
  rating?: number | null;
  notes?: string | null;
  created_at?: Date;
  updated_at?: Date;
};